### ISSUE TITLE
teaching insert with specified columns

### ISSUE THREAD

**Issue by siandav** [ironhack-labs/lab-sql-5#2]
in the syllabus we do not teach insert with selected columns as a method/ option yet it is needed in the lab. 

please add to syllabus 

@sandrabosk

**Comment by sandrabosk** [comment]
@haggarw3 please make sure we take this into account - and thank you as usual. thanks @siandav for reporting.

**Comment by ironhack-edu** [comment]
@haggarw3 hey mansh, has this been resolved?
